export const ROLES = {
  ADMIN: 'administrador',
  SUPERVENDEDOR: 'supervendedor',
  VENDEDOR: 'vendedor',
  REPARTIDOR: 'repartidor',
} as const

export type Role = typeof ROLES[keyof typeof ROLES]

export const PERMISSIONS = {
  // Gestión de Usuarios
  VER_USUARIOS: [ROLES.ADMIN, ROLES.SUPERVENDEDOR],
  CREAR_USUARIOS: [ROLES.ADMIN, ROLES.SUPERVENDEDOR],
  EDITAR_USUARIOS: [ROLES.ADMIN, ROLES.SUPERVENDEDOR],
  CAMBIAR_ROLES: [ROLES.ADMIN],

  // Productos
  CREAR_PRODUCTOS: [ROLES.ADMIN, ROLES.SUPERVENDEDOR],
  EDITAR_PRODUCTOS: [ROLES.ADMIN, ROLES.SUPERVENDEDOR],
  ELIMINAR_PRODUCTOS: [ROLES.ADMIN, ROLES.SUPERVENDEDOR],
  VER_PRODUCTOS: [ROLES.ADMIN, ROLES.SUPERVENDEDOR, ROLES.VENDEDOR],

  // Clientes
  CREAR_CLIENTES: [ROLES.ADMIN, ROLES.SUPERVENDEDOR, ROLES.VENDEDOR],
  EDITAR_CLIENTES: [ROLES.ADMIN, ROLES.SUPERVENDEDOR, ROLES.VENDEDOR],
  ELIMINAR_CLIENTES: [ROLES.ADMIN, ROLES.SUPERVENDEDOR],
  VER_CLIENTES: [ROLES.ADMIN, ROLES.SUPERVENDEDOR, ROLES.VENDEDOR],

  // Pedidos
  CREAR_PEDIDOS: [ROLES.ADMIN, ROLES.SUPERVENDEDOR, ROLES.VENDEDOR],
  EDITAR_PEDIDOS: [ROLES.ADMIN, ROLES.SUPERVENDEDOR, ROLES.VENDEDOR],
  CANCELAR_PEDIDOS: [ROLES.ADMIN, ROLES.SUPERVENDEDOR],
  VER_PEDIDOS: [ROLES.ADMIN, ROLES.SUPERVENDEDOR, ROLES.VENDEDOR, ROLES.REPARTIDOR],

  // Ventas
  CREAR_VENTAS: [ROLES.ADMIN, ROLES.SUPERVENDEDOR, ROLES.VENDEDOR],
  VER_VENTAS: [ROLES.ADMIN, ROLES.SUPERVENDEDOR, ROLES.VENDEDOR],
  VER_REPORTES: [ROLES.ADMIN, ROLES.SUPERVENDEDOR],

  // Dashboard
  VER_DASHBOARD_COMPLETO: [ROLES.ADMIN, ROLES.SUPERVENDEDOR],
  VER_DASHBOARD_LIMITADO: [ROLES.VENDEDOR, ROLES.REPARTIDOR],
} as const

export function hasPermission(
  userRole: Role | null | undefined,
  permission: keyof typeof PERMISSIONS
): boolean {
  if (!userRole) return false
  return PERMISSIONS[permission].includes(userRole as any)
}

export function isAdmin(userRole: Role | null | undefined): boolean {
  return userRole === ROLES.ADMIN
}
